### ISSUE TITLE
How to intercept/change the user parser ?

### ISSUE THREAD

**Issue by mingodad** [BenHanson/gram_grep#11]
I'm trying to add a symbol table functionality and for that I'm changing the master grammar like this:
```
-rhs : Literal | Name | '[' production ']' | rhs '?' | rhs '*' | rhs '+' | '(' production ')' ;
+rhs : Literal | rhs_name | '[' production ']' | rhs '?' | rhs '*' | rhs '+' | '(' production ')' ;
+rhs_name : Name ;
+rhs_name : Name "<:insert" Name ":>";
```
And when building the user parser I need to make the `"<:insert" Name ":>"` invisible and return only `Name`.
I've been trying this:
```
    grules.push("rhs_name", "Name");
    gs.master_parser.actions[grules.push("rhs_name",
        "Name '<:insert' Name ':>'")] = [](BuildUserParser& state)
    {
        const std::string lhs = "rhs_name";
        const std::string name = state.dollar(0);
        /* do the symbol table insertion here */
        state.gs.user_parser.grules.push(lhs, name);
    };
...
```
But it doesn't seem to work/fell right.

How to achieve something like that ?

See attached the full grammars that can be viewd¡ed/tested on https://mingodad.github.io/parsertl-playground/playground/.

symbol-table-playground-master.g is the grammar and symbol-table-pnet-c.g is the input source .

[symbol-table-playground-master.zip](https://github.com/BenHanson/gram_grep/files/12440049/symbol-table-playground-master.zip)

**Comment by mingodad** [comment]
Looking through the `Add semantic actions` example in http://benhanson.net/parsertl.html it seems that I need to manage it myself what's a bit of work.
Would be nice if the `parsertl::parse` could accept an action a lambda that could check if it would manage any reduction or leave then to be managed the standard way.

**Comment by BenHanson** [comment]
Both the lexer and parser generator libraries are explicitly designed to perform their function and only their function.

I'm not aiming for maximum convenience, I'm aiming for making things possible at all without resorting to flex and bison.
