### ISSUE TITLE
Missing escape char ?

### ISSUE THREAD

**Issue by mingodad** [BenHanson/gram_grep#12]
On this line https://github.com/BenHanson/gram_grep/blob/e90d24e7632ea06800cb9f4bb7151f674cb4fcdb/main.cpp#L2751 it seems that the `^` character is missing the `\` escape.

**Comment by BenHanson** [comment]
There is no need to escape the '^' as it only has a special meaning at the beginning of the regex string or the first char in a charset.

**Comment by mingodad** [comment]
Thank you for reply !
Looking at it after your reply I can see that probably I was misinterpreting the `?` following the `[^` as an optional operator instead of a bare character.

**Comment by mingodad** [comment]
And looking again I can see that the `?` character following the `\[^` is indeed an optional operator, I've messed up my interpretation of it, sorry by the noise !
