### ISSUE TITLE
Please choose a license

### ISSUE THREAD

**Issue by musicinmybrain** [BenHanson/gram_grep#17]
Please declare a license for `gram_grep` and include a license file in the repository.

Without an explicit license, `gram_grep` cannot be packaged in Linux distributions.

**Comment by musicinmybrain** [comment]
Starting to version and tag releases of `gram_grep` and its dependencies `lexertl17`, `parsertl17`, and `wildcardtl` would make life a lot easier too – see https://release-monitoring.org/ – but that’s a separate issue.

**Comment by BenHanson** [comment]
I have added LICENCE.txt.

I will tag releases too over the weekend.

Thanks for your help!

**Comment by BenHanson** [comment]
I have created releases for lexertl17, parsertl17, wildcardtl and gram_grep

**Comment by musicinmybrain** [comment]
> I have created releases for lexertl17, parsertl17, wildcardtl and gram_grep

I appreciate this! Should the CMake project versions, e.g.

https://github.com/BenHanson/lexertl17/blob/65aa5db76e7748082502deb982da4933d9f9c24e/CMakeLists.txt#L10

be updated from `0.1.0` to match the release tags? This version does appear in `lexertlConfigVersion.cmake` and is the machine-readable version number from the perspective of CMake users.

**Comment by BenHanson** [comment]
Do I have to tag a new version to do this?

Thanks,

Ben

**Comment by musicinmybrain** [comment]
What you’ve done looks good. Thanks. I have submitted `lexertl17`, `parsertl17`, and `wildcardtl` for new-package review in Fedora, and I’ll follow up with `gram_grep` soon.

**Comment by BenHanson** [comment]
Thanks a lot
