### ISSUE TITLE
comments grammar incorrectly interprets quoted comment syntax

### ISSUE THREAD

**Issue by rconde01** [BenHanson/gram_grep#20]
given `test.cpp`
```
int main(){

   zoot("/*");

   int five = 5;

   zoot("*/");
}
```
The command:
```
gram_grep.exe .\test.cpp -f .\sample_configs\comments.g -T five
```
gives:
```
.\test.cpp(5):   int five = 5;
Matches: 1    Matching files: 1    Total files searched: 1
```

**Comment by BenHanson** [comment]
I have updated comments.g

**Comment by BenHanson** [comment]
I remember now why it is done this way. If you want to do `-vf comments.g`, then you don't want to exclude comments.

You can combine excluding strings though:
```
gram_grep -vf sample_configs\string.g -f comments.g -T five
```
This seems like the best compromise to me.

**Comment by BenHanson** [comment]
I remember now why it is done this way. If you want to do `-vf sample_configs\comments.g`, then you don't want to exclude strings.

You can combine excluding strings though:
```
gram_grep -vf sample_configs\string.g -f sample_configs\comments.g -T five
```
This seems like the best compromise to me (if you disagree you can update the configs to your own liking).

**Comment by BenHanson** [comment]
I have updated  comments.g to exclude C++ strings. Note that this file will no longer be suitable as is for searching C# code.
