### ISSUE TITLE
Mismatch between macro name definitions

### ISSUE THREAD

**Issue by mingodad** [BenHanson/gram_grep#21]
Looking through the master grammar I found that it accept names for macros with this definition:
https://github.com/BenHanson/gram_grep/blob/2a50c84fff154f8ea464ac06af52c565e3d23782/parser.cpp#L911-L912

But accepts a different name definition for it's usage:
https://github.com/BenHanson/gram_grep/blob/2a50c84fff154f8ea464ac06af52c565e3d23782/parser.cpp#L936-L937

**Comment by BenHanson** [comment]
Done
