### ISSUE TITLE
Lowering down minimum C++ version needed

### ISSUE THREAD

**Issue by mingodad** [BenHanson/gram_grep#24]
If we replace this line:
https://github.com/BenHanson/gram_grep/blob/7ca7ef0f6f46299c247304e5283aea34bb7456b2/parser.cpp#L46
by:
```
std::string ret = unescape(std::string_view(first, second-first));
```
Then `gram_grep` can be built with `-std=c++17` instead of `-std=c++20`.

**Comment by BenHanson** [comment]
OK, but I am planning on using more C++20 features. I am being more conservative with the libraries, but it makes no sense to be held back by old versions when it comes to applications. After all C++23 is here and C++26 will be here soon!
